from django.urls import path

from apps.provider.views.staff import (ActivateTermsDocumentAPI,
                                       CreatePaymentProviderAPI,
                                       CreatePaymentProviderCredsAPI,
                                       CreateProviderWebhookAPI,
                                       CreateTermDocumentAPI,
                                       GetPaymentProviderCredsAPI,
                                       ListProviderWebhookAPI, ListTermsAPI,
                                       ListWebhookEventsAPI,
                                       ProviderLogoUploadAPI,
                                       RemoveTermDocumentAPI,
                                       UpdatePaymentProviderAPI,
                                       UpdatePaymentProviderCredsAPI)
from apps.provider.views.webhooks import (GetConsumerWebhookEventsAPI,
                                          GetMerchantWebhookEventsAPI,
                                          GetWebhookEventDetailsAPI,
                                          ProcessWebhookEventAPI)

urlpatterns = [
    path(
        "create/",
        CreatePaymentProviderAPI.as_view(),
    ),
    path(
        "update/",
        UpdatePaymentProviderAPI.as_view(),
    ),
    path(
        "logo/update/",
        ProviderLogoUploadAPI.as_view(),
    ),
    path(
        "creds/create/",
        CreatePaymentProviderCredsAPI.as_view(),
    ),
    path(
        "creds/update/",
        UpdatePaymentProviderCredsAPI.as_view(),
    ),
    path(
        "creds/<int:provider_id>/",
        GetPaymentProviderCredsAPI.as_view(),
    ),
    path(
        "terms/create/",
        CreateTermDocumentAPI.as_view(),
    ),
    path(
        "terms/deactivate/",
        RemoveTermDocumentAPI.as_view(),
    ),
    path(
        "terms/reactivate/",
        ActivateTermsDocumentAPI.as_view(),
    ),
    path(
        "terms/",
        ListTermsAPI.as_view(),
    ),
    path(
        "create-webhook/",
        CreateProviderWebhookAPI.as_view(),
    ),
    path(
        "active-webhooks/",
        ListProviderWebhookAPI.as_view(),
    ),
    path(
        "webhook/<int:webhook_id>/events/",
        ListWebhookEventsAPI.as_view(),
    ),
    path(
        "webhook/merchant/<uuid:merchant_id>/events/",
        GetMerchantWebhookEventsAPI.as_view(),
    ),
    path(
        "webhook/consumer/<uuid:consumer_id>/events/",
        GetConsumerWebhookEventsAPI.as_view(),
    ),
    path(
        "webhook/events/<int:event_id>/process/",
        ProcessWebhookEventAPI.as_view(),
    ),
    path(
        "webhook/events/<int:event_id>/details/",
        GetWebhookEventDetailsAPI.as_view(),
    ),
]
