# Generated by Django 3.1.5 on 2021-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0002_auto_20210301_0623"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltyprogram",
            name="reward_value_maximum",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6
            ),
        ),
    ]
