# Generated by Django 3.1.5 on 2021-03-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_auto_20210212_1239"),
        ("reward", "0004_auto_20210302_0958"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashreward",
            name="consumer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_rewards",
                to="account.consumeraccount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voucherreward",
            name="consumer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_rewards",
                to="account.consumeraccount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voucherreward",
            name="value_maximum",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6
            ),
        ),
    ]
