# Generated by Django 3.1.5 on 2021-03-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0009_auto_20210304_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardevent',
            old_name='amount',
            new_name='value',
        ),
    ]
