# Generated by Django 3.1.5 on 2021-03-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_auto_20210302_1059"),
        ("reward", "0010_auto_20210304_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardusageitem",
            name="is_reclaimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rewardevent",
            name="value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rewardusage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_usages",
                to="order.order",
            ),
        ),
    ]
