# Generated by Django 3.1.5 on 2021-03-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0011_auto_20210305_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardevent",
            name="voucher_reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="reward.voucherreward",
            ),
        ),
    ]
