# Generated by Django 3.1.5 on 2021-03-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210308_1135'),
        ('reward', '0012_auto_20210307_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_usages', to='order.order'),
        ),
    ]
