# Generated by Django 3.1.5 on 2021-03-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_auto_20210212_1239"),
        ("reward", "0014_auto_20210314_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardusage",
            name="consumer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.consumeraccount",
            ),
        ),
    ]
