# Generated by Django 3.1.5 on 2021-03-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_auto_20210212_1239"),
        ("reward", "0015_rewardusage_consumer"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardusage",
            name="is_first_time_credited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rewardusage",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.merchantaccount",
            ),
        ),
    ]
