# Generated by Django 3.1.1 on 2020-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficialowner",
            name="is_us_citizen",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="controllerdetails",
            name="is_us_citizen",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
