# Generated by Django 3.1.1 on 2020-12-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20201211_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorporationdetails',
            name='ein_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
