# Generated by Django 3.1.1 on 2020-12-21 13:06

from django.db import migrations, models

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0009_auto_20201216_0711"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficialowner",
            name="dwolla_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="beneficialowner",
            name="status",
            field=db.models.fields.enum.ChoiceEnumField(
                default=0,
                help_text="Status for the beneficial owner with dwolla.",
            ),
        ),
    ]
