# Generated by Django 3.1.1 on 2020-12-22 05:51

import db.models.fields.enum
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_auto_20201221_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficialowner',
            name='status',
            field=db.models.fields.enum.ChoiceEnumField(help_text='Status for the beneficial owner with dwolla.'),
        ),
    ]
