# Generated by Django 3.1.1 on 2020-12-22 06:46

from django.db import migrations, models

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0011_auto_20201222_0551"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficialowner",
            name="verification_docs_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beneficialowner",
            name="verification_document_status",
            field=db.models.fields.enum.ChoiceEnumField(
                default=0,
                help_text="Status for the verification document with dwolla.",
            ),
        ),
        migrations.AddField(
            model_name="controllerdetails",
            name="verification_docs_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="controllerdetails",
            name="verification_document_status",
            field=db.models.fields.enum.ChoiceEnumField(
                default=0,
                help_text="Status for the verification document with dwolla.",
            ),
        ),
        migrations.AddField(
            model_name="incorporationdetails",
            name="verification_document_status",
            field=db.models.fields.enum.ChoiceEnumField(
                default=0,
                help_text="Status for the verification document with dwolla.",
            ),
        ),
    ]
