# Generated by Django 3.1.1 on 2020-12-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0013_auto_20201222_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficialowner',
            old_name='verification_docs_required',
            new_name='verification_document_required',
        ),
        migrations.RenameField(
            model_name='controllerdetails',
            old_name='verification_docs_required',
            new_name='verification_document_required',
        ),
    ]
