# Generated by Django 3.1.1 on 2020-12-22 07:00

import db.models.fields.enum
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0014_auto_20201222_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorporationconsent',
            name='verification_document_status',
            field=db.models.fields.enum.ChoiceEnumField(default=0, help_text='Status for the verification document with dwolla.'),
        ),
    ]
