# Generated by Django 3.1.1 on 2020-12-22 07:00

import db.models.fields.enum
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0015_incorporationconsent_verification_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorporationconsent',
            name='verification_document_status',
            field=db.models.fields.enum.ChoiceEnumField(help_text='Status for the verification document with dwolla.'),
        ),
    ]
