# Generated by Django 3.1.1 on 2020-12-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0021_auto_20201222_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="incorporationdetails",
            name="industry_classification",
            field=models.CharField(default="Food", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incorporationdetails",
            name="industry_classification_id",
            field=models.CharField(
                default="9ed3f671-7d6f-11e3-803c-5404a6144203", max_length=64
            ),
            preserve_default=False,
        ),
    ]
