# Generated by Django 3.1.1 on 2020-12-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0022_auto_20201223_0551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficialowner",
            name="ssn",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="controllerdetails",
            name="ssn",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
