# Generated by Django 3.1.1 on 2020-12-24 08:40

import db.models.fields.choice
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0023_auto_20201223_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficialowner',
            name='verification_document_type',
            field=db.models.fields.choice.ChoiceCharEnumField(default='not_applicable', max_length=32),
        ),
        migrations.AlterField(
            model_name='controllerdetails',
            name='verification_document_type',
            field=db.models.fields.choice.ChoiceCharEnumField(default='not_applicable', max_length=32),
        ),
        migrations.AlterField(
            model_name='incorporationdetails',
            name='verification_document_type',
            field=db.models.fields.choice.ChoiceCharEnumField(default='not_applicable', max_length=32),
        ),
    ]
