# Generated by Django 3.1.1 on 2020-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0024_auto_20201224_0840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantprofile",
            name="category",
            field=models.CharField(default="auto_services", max_length=64),
        ),
        migrations.AlterField(
            model_name="merchantprofile",
            name="sub_category",
            field=models.CharField(default="audio-and-video", max_length=64),
        ),
    ]
