# Generated by Django 3.1.1 on 2021-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0027_auto_20210105_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantprofile",
            name="category",
            field=models.CharField(default="auto_service", max_length=64),
        ),
        migrations.AlterField(
            model_name="merchantprofile",
            name="sub_category",
            field=models.CharField(
                default="automotive-audio-and-entertainment", max_length=64
            ),
        ),
    ]
