# Generated by Django 3.1.5 on 2021-01-14 04:08

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_merchantaccount_is_active"),
        ("merchant", "0029_auto_20210114_0358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantoperationhours",
            name="close_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="merchantoperationhours",
            name="day",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=3),
        ),
        migrations.AlterField(
            model_name="merchantoperationhours",
            name="open_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="merchantoperationhours",
            unique_together={("merchant", "day")},
        ),
        migrations.AlterModelTable(
            name="merchantoperationhours",
            table="merchant_operation_hours",
        ),
    ]
