# Generated by Django 3.1.5 on 2021-01-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0031_auto_20210114_0716"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantprofile",
            name="category",
        ),
        migrations.RemoveField(
            model_name="merchantprofile",
            name="sub_category",
        ),
        migrations.DeleteModel(
            name="MerchantCategory",
        ),
    ]
