# Generated by Django 3.1.5 on 2021-01-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_auto_20210114_0554"),
        ("merchant", "0034_auto_20210114_1124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantcategory",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="account.merchantaccount",
            ),
        ),
    ]
