# Generated by Django 3.1.5 on 2021-01-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_auto_20210114_0554"),
        ("merchant", "0035_auto_20210114_1127"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codesandprotocols",
            old_name="ourdoor_seating",
            new_name="outdoor_seating",
        ),
        migrations.AlterField(
            model_name="merchantprofile",
            name="merchant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="account.merchantaccount",
            ),
        ),
    ]
