# Generated by Django 3.1.5 on 2021-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0037_merchantcategory_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesandprotocols',
            name='contactless_payments',
        ),
    ]
