# Generated by Django 3.1.5 on 2021-01-22 16:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import db.models.fields.choice
import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0019_auto_20210122_1625"),
        ("box", "0005_boxfile_in_use"),
        ("merchant", "0039_remove_merchantprofile_neighborhood"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControllerVerificationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("all_failure_reasons", models.JSONField(default=dict)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "document_type",
                    db.models.fields.choice.ChoiceCharEnumField(
                        default="not_applicable", max_length=32
                    ),
                ),
                (
                    "status",
                    db.models.fields.enum.ChoiceEnumField(
                        default=4,
                        help_text="Status for the verification document with dwolla.",
                    ),
                ),
                ("dwolla_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "controller_verification_document",
            },
        ),
        migrations.CreateModel(
            name="IncorporationVerificationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("all_failure_reasons", models.JSONField(default=dict)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "document_type",
                    db.models.fields.choice.ChoiceCharEnumField(
                        default="not_applicable", max_length=32
                    ),
                ),
                (
                    "status",
                    db.models.fields.enum.ChoiceEnumField(
                        default=4,
                        help_text="Status for the verification document with dwolla.",
                    ),
                ),
                ("dwolla_id", models.CharField(blank=True, max_length=64)),
                (
                    "verification_document_type",
                    db.models.fields.choice.ChoiceCharEnumField(
                        default="not_applicable", max_length=32
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incorporationverificationdocument_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incorporationverificationdocument_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="box.boxfile",
                    ),
                ),
                (
                    "incorporation_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.merchantaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incorporationverificationdocument_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inc_details_verification_document",
            },
        ),
        migrations.CreateModel(
            name="OnboardingConsent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=256)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboardingconsent_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboardingconsent_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.merchantaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboardingconsent_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merchant_onboarding_consent",
            },
        ),
        migrations.CreateModel(
            name="OwnerVerificationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("all_failure_reasons", models.JSONField(default=dict)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "document_type",
                    db.models.fields.choice.ChoiceCharEnumField(
                        default="not_applicable", max_length=32
                    ),
                ),
                (
                    "status",
                    db.models.fields.enum.ChoiceEnumField(
                        default=4,
                        help_text="Status for the verification document with dwolla.",
                    ),
                ),
                ("dwolla_id", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerverificationdocument_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerverificationdocument_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="box.boxfile",
                    ),
                ),
            ],
            options={
                "db_table": "owner_verification_document",
            },
        ),
        migrations.RemoveField(
            model_name="beneficialowner",
            name="dwolla_document_id",
        ),
        migrations.RemoveField(
            model_name="beneficialowner",
            name="verification_document_file",
        ),
        migrations.RemoveField(
            model_name="beneficialowner",
            name="verification_document_status",
        ),
        migrations.RemoveField(
            model_name="beneficialowner",
            name="verification_document_type",
        ),
        migrations.RemoveField(
            model_name="controllerdetails",
            name="dwolla_document_id",
        ),
        migrations.RemoveField(
            model_name="controllerdetails",
            name="verification_document_file",
        ),
        migrations.RemoveField(
            model_name="controllerdetails",
            name="verification_document_status",
        ),
        migrations.RemoveField(
            model_name="controllerdetails",
            name="verification_document_type",
        ),
        migrations.RemoveField(
            model_name="incorporationdetails",
            name="dwolla_document_id",
        ),
        migrations.RemoveField(
            model_name="incorporationdetails",
            name="verification_document_file",
        ),
        migrations.RemoveField(
            model_name="incorporationdetails",
            name="verification_document_status",
        ),
        migrations.RemoveField(
            model_name="incorporationdetails",
            name="verification_document_type",
        ),
        migrations.DeleteModel(
            name="IncorporationConsent",
        ),
        migrations.AddField(
            model_name="ownerverificationdocument",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.beneficialowner",
            ),
        ),
        migrations.AddField(
            model_name="ownerverificationdocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerverificationdocument_updated_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="controllerverificationdocument",
            name="controller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.controllerdetails",
            ),
        ),
        migrations.AddField(
            model_name="controllerverificationdocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controllerverificationdocument_created_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="controllerverificationdocument",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controllerverificationdocument_deleted_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="controllerverificationdocument",
            name="document_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="box.boxfile",
            ),
        ),
        migrations.AddField(
            model_name="controllerverificationdocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controllerverificationdocument_updated_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
