# Generated by Django 3.1.5 on 2021-01-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_auto_20210122_1625"),
        ("merchant", "0040_auto_20210122_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllerverificationdocument",
            name="controller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="merchant.controllerdetails",
            ),
        ),
        migrations.AlterField(
            model_name="incorporationverificationdocument",
            name="incorporation_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="account.merchantaccount",
            ),
        ),
        migrations.AlterField(
            model_name="ownerverificationdocument",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="merchant.beneficialowner",
            ),
        ),
    ]
