# Generated by Django 3.1.5 on 2021-01-22 16:46

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0041_auto_20210122_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficialowner",
            name="status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                help_text="Status for the beneficial owner with dwolla.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="controllerverificationdocument",
            name="status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="not_applicable",
                help_text="Status for the verification document with dwolla.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="incorporationverificationdocument",
            name="status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="not_applicable",
                help_text="Status for the verification document with dwolla.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="ownerverificationdocument",
            name="status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="not_applicable",
                help_text="Status for the verification document with dwolla.",
                max_length=128,
            ),
        ),
    ]
