# Generated by Django 3.1.5 on 2021-01-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_auto_20210122_1711"),
        ("merchant", "0042_auto_20210122_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficialowner",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficial_owners",
                to="account.merchantaccount",
            ),
        ),
        migrations.AlterField(
            model_name="controllerdetails",
            name="merchant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controller_details",
                to="account.merchantaccount",
            ),
        ),
        migrations.AlterField(
            model_name="incorporationdetails",
            name="merchant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incorporation_details",
                to="account.merchantaccount",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingconsent",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_consents",
                to="account.merchantaccount",
            ),
        ),
    ]
