# Generated by Django 3.1.5 on 2021-01-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0043_auto_20210122_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incorporationverificationdocument",
            name="incorporation_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="merchant.incorporationdetails",
            ),
        ),
    ]
