# Generated by Django 3.1.5 on 2021-01-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0044_auto_20210123_0538"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incorporationverificationdocument",
            name="verification_document_type",
        ),
    ]
