# Generated by Django 3.1.5 on 2021-02-22 06:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0046_auto_20210211_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureaccessrole",
            name="bank_accounts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="customers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="is_full_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="payment_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="payment_requests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="qr_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="refunds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="settlements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="store_profile",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="featureaccessrole",
            name="team_management",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="accountmember",
            name="role",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_member",
                to="merchant.featureaccessrole",
            ),
        ),
        migrations.AlterField(
            model_name="memberinvite",
            name="role",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_invite",
                to="merchant.featureaccessrole",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureaccessrole",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="banking",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="beneficiaries",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="description",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="role_name",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="team_and_roles",
        ),
        migrations.RemoveField(
            model_name="featureaccessrole",
            name="transactions",
        ),
    ]
