# Generated by Django 3.1.5 on 2021-02-22 06:40

from django.db import migrations


def migrate_data(apps, schema_editor):
    FeatureAccessRole = apps.get_model("merchant", "FeatureAccessRole")
    for role in FeatureAccessRole.objects.all():
        if role.is_super_admin:
            role.is_full_access = True
            role.payment_requests = ["CREATE", "VIEW"]
            role.payment_history = ["PARTIAL_VIEW", "VIEW"]
            role.settlements = ["VIEW", "PARTIAL_VIEW"]
            role.refunds = ["CREATE", "VIEW", "PARTIAL_VIEW"]
            role.disputes = ["PARTIAL_VIEW", "VIEW"]
            role.customers = ["PARTIAL_VIEW", "VIEW"]
            role.bank_accounts = ["CREATE", "VIEW", "DELETE"]
            role.qr_codes = ["CREATE", "UPDATE", "VIEW"]
            role.store_profile = ["UPDATE", "VIEW"]
            role.team_management = ["CREATE", "UPDATE", "VIEW", "DELETE"]
            role.save()


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0047_auto_20210222_0639"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
