# Generated by Django 3.1.5 on 2021-03-15 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0053_auto_20210315_0356"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureaccessrole",
            name="merchant_settings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
