# Generated by Django 3.1.5 on 2021-04-24 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import db.models.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0063_paymentqrcode_register_name"),
        ("merchant", "0057_possession_posstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="posstaff",
            name="register",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.paymentqrcode",
            ),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="login_pin",
            field=db.models.fields.encrypted.EncryptedCharField(
                blank=True, default=None, max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="login_token_expire_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="pin_last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="shift_end",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="shift_start",
            field=models.TimeField(null=True),
        ),
    ]
