# Generated by Django 3.1.5 on 2021-04-24 12:31

from django.db import migrations

import db.models.fields.encrypted
import utils.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0058_auto_20210424_0853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posstaff",
            name="login_token",
            field=db.models.fields.encrypted.EncryptedCharField(
                default=utils.shortcuts.rand_str, max_length=2048
            ),
        ),
    ]
