# Generated by Django 3.1.5 on 2021-04-24 12:55

from django.db import migrations

import db.models.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0059_auto_20210424_1231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posstaff",
            name="login_pin",
            field=db.models.fields.encrypted.EncryptedCharField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
    ]
