# Generated by Django 3.1.5 on 2021-04-07 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0027_auto_20210212_1239'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='C2CInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default=None, max_length=10, null=True)),
                ('phone_number_country', models.CharField(default='US', max_length=2)),
                ('consumer_name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_used', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.consumeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2cinvite_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2cinvite_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2cinvite_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'c2c_invite',
            },
        ),
        migrations.CreateModel(
            name='C2BInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default=None, max_length=10, null=True)),
                ('phone_number_country', models.CharField(default='US', max_length=2)),
                ('merchant_name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_used', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.consumeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2binvite_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2binvite_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2binvite_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'c2b_invite',
            },
        ),
        migrations.CreateModel(
            name='B2CInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('consumer_name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(default=None, max_length=10, null=True)),
                ('phone_number_country', models.CharField(default='US', max_length=2)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2cinvite_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2cinvite_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchantaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2cinvite_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'b2c_invite',
            },
        ),
        migrations.CreateModel(
            name='B2BInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('merchant_name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(default=None, max_length=10, null=True)),
                ('phone_number_country', models.CharField(default='US', max_length=2)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2binvite_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2binvite_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchantaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2binvite_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'b2b_invite',
            },
        ),
    ]
