# Generated by Django 3.1.1 on 2020-12-07 12:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import db.models.fields.bounded
import db.models.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_contact_number_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authenticator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "type",
                    db.models.fields.bounded.BoundedPositiveIntegerField(
                        choices=[(1, "Authenticator App"), (2, "Text Message")]
                    ),
                ),
                (
                    "config",
                    db.models.fields.encrypted.EncryptedPickledObjectField(
                        editable=False
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        null=True, verbose_name="last used at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "authenticator",
                "verbose_name_plural": "authenticators",
                "db_table": "auth_authenticator",
                "unique_together": {("user", "type")},
            },
        ),
    ]
