# Generated by Django 3.1.1 on 2020-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_authenticator"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_password_expired",
            field=models.BooleanField(
                default=False,
                help_text="If set to true then the user needs to change the password on next sign in.",
                verbose_name="password expired",
            ),
        ),
    ]
