# Generated by Django 3.1.1 on 2020-12-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20201207_1706'),
        ('user', '0004_user_is_password_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.boxfile'),
        ),
    ]
