# Generated by Django 3.1.1 on 2020-12-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_auto_20201207_1743"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="contact_number_verified",
            new_name="phone_number_verified",
        ),
    ]
