# Generated by Django 3.1.1 on 2020-12-11 15:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20201208_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authenticator",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userpasswordreset",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
