# Generated by Django 3.1.1 on 2020-12-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201216_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number_country',
            field=models.CharField(default='US', max_length=2),
        ),
    ]
