# Generated by Django 3.1.1 on 2020-12-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_phone_number_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.TextField(),
        ),
    ]
