# Generated by Django 3.1.5 on 2021-01-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_auto_20210104_0443"),
        ("user", "0013_auto_20201217_0440"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="user_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notification.userdevice",
            ),
        ),
    ]
