# Generated by Django 3.1.5 on 2021-01-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_auto_20210104_0443"),
        ("user", "0014_usersession_user_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="user_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sessions",
                to="notification.userdevice",
            ),
        ),
    ]
