# Generated by Django 3.1.5 on 2021-02-11 13:59

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_auto_20210124_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="internal", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "phone_number", "customer_type")},
        ),
    ]
