# Generated by Django 3.1.5 on 2021-02-26 12:24

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_auto_20210211_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="user-avatars"
            ),
        ),
    ]
