# Generated by Django 3.1.5 on 2021-02-10 07:03

import uuid

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("min_allowed_version", models.CharField(max_length=128)),
                ("new_version", models.CharField(max_length=128)),
                (
                    "platform",
                    db.models.fields.choice.ChoiceCharEnumField(max_length=8),
                ),
                ("store_url", models.URLField(max_length=256)),
                (
                    "api_env",
                    db.models.fields.choice.ChoiceCharEnumField(
                        max_length=32, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "app_metadata",
            },
        ),
    ]
