# Generated by Django 3.1.5 on 2021-02-10 07:16

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmetadata",
            name="api_env",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=32),
        ),
    ]
