# Generated by Django 3.1.5 on 2021-04-28 14:19

import db.models.fields.choice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmetadata',
            name='api_env',
            field=db.models.fields.choice.ChoiceCharEnumField(default='development', max_length=32),
        ),
        migrations.AddField(
            model_name='merchantmetadata',
            name='min_allowed_version',
            field=models.CharField(default='0.0.1', max_length=128),
        ),
        migrations.AddField(
            model_name='merchantmetadata',
            name='new_version',
            field=models.CharField(default='0.0.1', max_length=128),
        ),
        migrations.AddField(
            model_name='merchantmetadata',
            name='store_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
