# Generated by Django 3.1.1 on 2020-12-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentaccountopeningconsent", name="created_by",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningconsent", name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningconsent", name="payment_account",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningconsent", name="term",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningconsent", name="updated_by",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningcreds", name="created_by",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningcreds", name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningcreds", name="payment_account",
        ),
        migrations.RemoveField(
            model_name="paymentaccountopeningcreds", name="updated_by",
        ),
        migrations.RemoveField(
            model_name="providerupdatewebhook", name="created_by",
        ),
        migrations.RemoveField(
            model_name="providerupdatewebhook", name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="providerupdatewebhook", name="provider",
        ),
        migrations.RemoveField(
            model_name="providerupdatewebhook", name="updated_by",
        ),
        migrations.DeleteModel(name="PaymentAccount",),
        migrations.DeleteModel(name="PaymentAccountOpeningConsent",),
        migrations.DeleteModel(name="PaymentAccountOpeningCreds",),
        migrations.DeleteModel(name="ProviderUpdateWebhook",),
    ]
