# Generated by Django 3.1.5 on 2021-01-08 08:48

from django.db import migrations

import db.models.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0004_auto_20210106_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentprovidercred",
            name="api_key",
            field=db.models.fields.encrypted.EncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovidercred",
            name="api_login_id",
            field=db.models.fields.encrypted.EncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovidercred",
            name="api_password",
            field=db.models.fields.encrypted.EncryptedCharField(
                blank=True, max_length=255
            ),
        ),
    ]
