# Generated by Django 3.1.5 on 2021-01-08 09:04

import db.models.fields.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20210108_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproviderauth',
            name='auth_token',
            field=db.models.fields.encrypted.EncryptedCharField(max_length=1024),
        ),
    ]
