# Generated by Django 3.1.5 on 2021-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0008_auto_20210208_0617"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerwebhookevent",
            name="customer_dwolla_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="providerwebhookevent",
            name="event_timestamp",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
