# Generated by Django 3.1.1 on 2020-12-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxfile',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='boxfile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='boxfile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='boxfile',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='boxfile',
            name='updated_by',
        ),
    ]
