# Generated by Django 3.1.1 on 2020-12-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0002_auto_20201207_1705"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boxfile",
            options={},
        ),
        migrations.AlterModelTable(
            name="boxfile",
            table="boxfile",
        ),
    ]
