# Generated by Django 3.1.1 on 2020-12-11 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20201207_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxfile',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
