# Generated by Django 3.1.1 on 2020-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0004_auto_20201211_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxfile",
            name="in_use",
            field=models.BooleanField(default=False),
        ),
    ]
