# Generated by Django 3.1.5 on 2021-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0006_auto_20210303_0702"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rewardusage",
            name="loyalty_program",
        ),
        migrations.AddField(
            model_name="cashreward",
            name="is_full_used",
            field=models.BooleanField(default=False),
        ),
    ]
