# Generated by Django 3.1.1 on 2021-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_auto_20210104_0442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device_id",
            field=models.CharField(
                blank=True, default=None, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_tracking_id",
            field=models.CharField(
                blank=True, default=None, max_length=32, null=True, unique=True
            ),
        ),
    ]
