# Generated by Django 3.1.5 on 2021-03-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_staffpaymentnotificationsetting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffpaymentnotificationsetting",
            old_name="notitication_type",
            new_name="notification_type",
        ),
    ]
