# Generated by Django 3.1.1 on 2020-12-28 11:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20201221_1910"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_tracking_id",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("type", db.models.fields.enum.ChoiceEnumField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_events",
                        to="account.account",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_event",
            },
        ),
    ]
