# Generated by Django 3.1.1 on 2020-12-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_auto_20201228_1105"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderevent",
            old_name="type",
            new_name="event_type",
        ),
    ]
