# Generated by Django 3.1.5 on 2021-03-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_auto_20210302_0958"),
        ("order", "0005_order_rewards_credit_applied"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="rewards_credit_applied",
        ),
        migrations.AddField(
            model_name="order",
            name="cash_reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="rewards.cashreward",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_rewarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="total_return_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="voucher_reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="rewards.voucherreward",
            ),
        ),
    ]
