# Generated by Django 3.1.5 on 2021-03-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_auto_20210302_0958"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_return_amount",
        ),
    ]
