# Generated by Django 3.1.5 on 2021-03-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_auto_20210302_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="total_return_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6
            ),
        ),
    ]
