# Generated by Django 3.1.5 on 2021-03-02 10:55

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    for order in Order.objects.all():
        try:
            payment = order.payment
            order.total_return_amount = payment.refunded_amount
            order.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_auto_20210302_1054"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
