# Generated by Django 3.1.5 on 2021-03-08 10:46

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_auto_20210302_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                max_length=32, default="fixed_amount"
            ),
        ),
    ]
