# Generated by Django 3.1.5 on 2021-03-19 11:35

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def migrate_data(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")
    for payment in Payment.objects.all():
        try:
            order = payment.order
            order.total_return_amount = payment.refunded_amount
            if payment.captured_amount > Decimal(0.0):
                order.is_paid = True
            order.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_order_applied_voucher"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
