# Generated by Django 3.1.1 on 2020-11-30 16:48

from django.conf import settings
from django.db import migrations, models

import utils.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="dwolla_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="account",
            name="dwolla_correlation_id",
            field=models.CharField(
                default=utils.shortcuts.generate_uuid_hex,
                editable=False,
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consumeraccount",
            unique_together={("account", "user")},
        ),
    ]
