# Generated by Django 3.1.1 on 2020-12-11 15:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_auto_20201210_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="consumeraccount",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="merchantaccount",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
