# Generated by Django 3.1.1 on 2020-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201211_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeraccount',
            name='username',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
    ]
