# Generated by Django 3.1.1 on 2020-12-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_consumeraccount_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantaccount",
            name="company_name",
        ),
    ]
