# Generated by Django 3.1.1 on 2020-12-21 13:06

import db.models.fields.enum
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_merchantaccount_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeraccount',
            name='account_status',
            field=db.models.fields.enum.ChoiceEnumField(default=2, help_text='Status for the consumer account with dwolla.'),
        ),
    ]
