# Generated by Django 3.1.1 on 2020-12-21 19:07

from django.db import migrations, models

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_consumeraccount_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantaccount",
            name="certification_status",
            field=db.models.fields.enum.ChoiceEnumField(
                default=0,
                help_text="Status for the merchant beneficial owner certified with dwolla.",
            ),
        ),
        migrations.AddField(
            model_name="merchantaccount",
            name="is_certification_required",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
