# Generated by Django 3.1.1 on 2020-12-21 19:10

import db.models.fields.enum
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201221_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantaccount',
            name='certification_status',
            field=db.models.fields.enum.ChoiceEnumField(help_text='Status for the merchant beneficial owner certified with dwolla.'),
        ),
    ]
