# Generated by Django 3.1.1 on 2021-01-05 13:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0005_boxfile_in_use"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0012_auto_20201221_1910"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAccountOpeningConsent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("user_agent", models.TextField(editable=False)),
                ("ip_address", models.GenericIPAddressField(editable=False)),
                ("consent_timestamp", models.BigIntegerField(editable=False)),
                (
                    "account",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="account.account",
                    ),
                ),
                (
                    "payment_term_document",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="box.boxfile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_account_opening_consent",
            },
        ),
    ]
