# Generated by Django 3.1.1 on 2021-01-05 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0013_paymentaccountopeningconsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentaccountopeningconsent",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
