# Generated by Django 3.1.5 on 2021-01-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_merchantaccount_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantaccount",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="merchantaccount",
            name="company_email",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
