# Generated by Django 3.1.5 on 2021-01-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_auto_20210114_0554"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_verified_dwolla_customer",
            field=models.BooleanField(default=False),
        ),
    ]
