# Generated by Django 3.1.5 on 2021-01-21 12:20

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_account_is_verified_dwolla_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="dwolla_customer_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                help_text="Status for the account with dwolla.",
                default="not_sent",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="dwolla_customer_verification_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                help_text="Status for the consumer account with dwolla.",
                default="not_sent",
                max_length=64,
            ),
        ),
    ]
