# Generated by Django 3.1.5 on 2021-01-22 16:25

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_auto_20210121_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="dwolla_customer_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                help_text="Status for the account with dwolla.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="dwolla_customer_verification_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                help_text="Status for the consumer account with dwolla.",
                max_length=64,
            ),
        ),
    ]
