# Generated by Django 3.1.5 on 2021-01-22 17:11

from django.db import migrations, models

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_auto_20210122_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="certification_status",
            field=db.models.fields.enum.ChoiceEnumField(
                help_text="Status for the merchant beneficial owner certified with dwolla.",
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_certification_required",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
