# Generated by Django 3.1.5 on 2021-01-23 05:38

from django.db import migrations

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_auto_20210122_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="certification_status",
            field=db.models.fields.enum.ChoiceEnumField(
                help_text="Status for the merchant beneficial owner certified with dwolla."
            ),
        ),
    ]
