# Generated by Django 3.1.5 on 2021-01-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_auto_20210123_0538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumeraccount",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="merchantaccount",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchant",
                to="account.account",
            ),
        ),
    ]
