# Generated by Django 3.1.5 on 2021-01-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210125_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_reverification_needed',
            field=models.BooleanField(default=False),
        ),
    ]
