# Generated by Django 3.1.5 on 2021-01-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_account_is_reverification_needed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantaccount",
            name="account_status",
        ),
        migrations.RemoveField(
            model_name="merchantaccount",
            name="certification_status",
        ),
        migrations.RemoveField(
            model_name="merchantaccount",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="merchantaccount",
            name="is_certification_required",
        ),
    ]
