# Generated by Django 3.1.5 on 2021-01-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0005_boxfile_in_use"),
        ("account", "0024_auto_20210128_0509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentaccountopeningconsent",
            name="payment_term_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="box.boxfile",
            ),
        ),
    ]
