# Generated by Django 3.1.5 on 2021-02-11 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0025_auto_20210129_1206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumeraccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
