# Generated by Django 3.1.5 on 2021-02-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_auto_20210211_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantaccount",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="merchantaccount",
            name="company_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
