# Generated by Django 3.1.1 on 2020-12-14 11:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=2)),
                ("county", models.CharField(max_length=64)),
                ("area_code", models.CharField(blank=True, max_length=64)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="purposeofpayment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="purposeofpayment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="purposeofpayment",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="purposeofpayment",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="city",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="city",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="city",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="country",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="country",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="country",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="regionstate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="regionstate",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="regionstate",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="city",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="regionstate",
            name="u_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="ProviderPopCode",
        ),
        migrations.DeleteModel(
            name="PurposeOfPayment",
        ),
    ]
