# Generated by Django 3.1.1 on 2020-12-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_auto_20201214_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='lon',
        ),
    ]
