# Generated by Django 3.1.1 on 2020-11-30 11:23

import functools
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPspApiResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("request_time_taken", models.FloatField(null=True)),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("headers", models.JSONField()),
                ("content", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawpspapiresponse_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawpspapiresponse_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawpspapiresponse_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "raw_psp_api_response",},
        ),
        migrations.CreateModel(
            name="RawPspApiRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("origin", models.CharField(max_length=512)),
                ("endpoint", models.CharField(max_length=512)),
                ("query_params", models.CharField(blank=True, max_length=512)),
                ("headers", models.JSONField()),
                ("method", models.CharField(max_length=64)),
                ("data", models.JSONField(null=True)),
                (
                    "files",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FileField(
                            upload_to=functools.partial(
                                utils.shortcuts._update_filename,
                                *(),
                                **{
                                    "path": "tracking/request_files/",
                                    "prefix": "file",
                                }
                            )
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("request_errors", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawpspapirequest_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawpspapirequest_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tracking.rawpspapiresponse",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawpspapirequest_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "raw_psp_api_request",},
        ),
        migrations.CreateModel(
            name="PspApiRequestStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("api_errors", models.TextField(blank=True, null=True)),
                (
                    "exception_traceback",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="account.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pspapirequeststorage_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pspapirequeststorage_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "psp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="provider.paymentprovider",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.rawpspapirequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pspapirequeststorage_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "psp_api_request",},
        ),
        migrations.CreateModel(
            name="APIAccessLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("time_elapsed", models.FloatField(default=0.0)),
                (
                    "request_path",
                    models.CharField(db_index=True, max_length=1024),
                ),
                (
                    "api_view",
                    models.CharField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "view_method",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("remote_addr", models.GenericIPAddressField()),
                ("host", models.URLField()),
                ("ua_config", models.JSONField(blank=True, null=True)),
                ("method", models.CharField(max_length=10)),
                ("query_params", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("errors", models.TextField(blank=True, null=True)),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cf_ray_id", models.CharField(blank=True, max_length=256)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apiaccesslog_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apiaccesslog_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apiaccesslog_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "api_request_log",},
        ),
    ]
