# Generated by Django 3.1.1 on 2021-01-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_auto_20210105_1440"),
        ("tracking", "0002_auto_20201211_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pspapirequeststorage",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.account",
            ),
        ),
    ]
