# Generated by Django 3.1.1 on 2020-12-03 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.shortcuts
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0003_bankaccount_is_primary'),
        ('account', '0004_auto_20201201_1137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('payment_amount', models.FloatField()),
                ('payment_currency', models.CharField(default='USD', max_length=3)),
                ('fee_value', models.FloatField(default=0.0)),
                ('fee_currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(default='NOT_SENT', max_length=128)),
                ('correlation_id', models.CharField(default=utils.shortcuts.generate_uuid_hex, editable=False, max_length=40, unique=True)),
                ('dwolla_id', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_bank_account', to='banking.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_bank_account', to='banking.bankaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='PaymentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('daily_send_limit', models.FloatField(default=500.0)),
                ('weekly_send_limit', models.FloatField(default=5000.0)),
                ('daily_usage', models.FloatField(default=0.0)),
                ('daily_usage_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('weekly_usage', models.FloatField(default=0.0)),
                ('weekly_usage_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('passcode_required_minimum', models.FloatField(default=100.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentregister_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentregister_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentregister_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_account',
            },
        ),
    ]
