# Generated by Django 3.1.1 on 2020-12-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentregister',
            table='payment_register',
        ),
    ]
