# Generated by Django 2.1.7 on 2020-08-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiary", "0002_auto_20200828_1828"),
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("provider", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratequote",
            name="payment_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="provider.PaymentAccount",
            ),
        ),
        migrations.AddField(
            model_name="ratequote",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratequote_updated_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.Account",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="beneficiary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="beneficiary.Beneficiary",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentrequest_created_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentrequest_deleted_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentrequest_updated_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
