# Generated by Django 3.1.1 on 2020-12-11 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201207_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentregister',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
