# Generated by Django 2.1.7 on 2020-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_auto_20200828_1828"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="purpose_of_payment_code",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
