# Generated by Django 3.1.1 on 2020-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_paymentrequest_purpose_of_payment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="ref_document",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_confirmation_file",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
