# Generated by Django 3.1.1 on 2020-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201211_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='fee_value',
            new_name='fee_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tip_amount',
            field=models.FloatField(default=0),
        ),
    ]
