# Generated by Django 3.1.1 on 2020-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_auto_20200905_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="status",
            field=models.CharField(default="DEFAULT", max_length=128),
        ),
        migrations.AlterModelTable(
            name="paymentrequest", table="payment_request",
        ),
        migrations.AlterModelTable(name="ratequote", table="rate_quote",),
        migrations.AlterModelTable(name="transaction", table="transaction",),
        migrations.AlterModelTable(
            name="transactioncancellationrequest",
            table="transaction_cancellation_request",
        ),
    ]
