# Generated by Django 3.1.1 on 2020-12-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20201216_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='fee_currency',
        ),
    ]
