# Generated by Django 3.1.1 on 2020-12-17 14:55

from django.db import migrations

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_remove_paymentrequest_tip_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="status",
            field=db.models.fields.enum.ChoiceEnumField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=db.models.fields.enum.ChoiceEnumField(),
        ),
    ]
