# Generated by Django 3.1.1 on 2020-12-23 13:02

import db.models.fields.choice
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20201217_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='payment_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_currency',
            new_name='currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tranasction_type',
            field=db.models.fields.choice.ChoiceCharEnumField(default="payment", max_length=64),
        ),
    ]
