# Generated by Django 3.1.1 on 2020-12-23 13:10

import db.models.fields.choice
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20201223_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tranasction_type',
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=64),
        ),
    ]
