# Generated by Django 3.1.1 on 2020-12-24 13:25

import db.models.fields.choice
import db.models.fields.enum
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('account', '0012_auto_20201221_1910'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0013_auto_20201223_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('gateway', models.CharField(default='dwolla', max_length=64)),
                ('payment_method_type', db.models.fields.choice.ChoiceCharEnumField(max_length=64)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', db.models.fields.enum.ChoiceEnumField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='account',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='requested_to',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_qrcode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tip_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_payment_requests', to='account.account'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_payment_requests', to='account.account'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='order.order'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('refund_type', db.models.fields.choice.ChoiceCharEnumField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', db.models.fields.enum.ChoiceEnumField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.payment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund',
            },
        ),
        migrations.CreateModel(
            name='QrCodePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', db.models.fields.enum.ChoiceEnumField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodepayment_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodepayment_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_payments', to='order.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_payments', to='payment.payment')),
                ('payment_qrcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcode_payments', to='payment.paymentqrcode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodepayment_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qrcode_payment',
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.payment'),
        ),
    ]
