# Generated by Django 3.1.1 on 2020-12-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0015_auto_20201224_1741"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="recipient",
            new_name="recipient_bank_account",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="sender",
            new_name="sender_bank_account",
        ),
        migrations.RemoveField(
            model_name="directmerchantpayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="status",
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_balance_at_checkout",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
