# Generated by Django 3.1.1 on 2020-12-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0004_auto_20201211_1541"),
        ("payment", "0016_auto_20201225_0442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="recipient_bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="recipient_transactions",
                to="banking.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sender_transactions",
                to="banking.bankaccount",
            ),
        ),
    ]
