# Generated by Django 3.1.1 on 2020-12-25 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20201221_1910"),
        ("payment", "0017_auto_20201225_0443"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="account",
        ),
        migrations.AddField(
            model_name="transaction",
            name="fee_bearer_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_success",
            field=models.BooleanField(default=False),
        ),
    ]
