# Generated by Django 3.1.1 on 2020-12-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_auto_20201225_0609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmerchantpayment",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_payments",
                to="payment.payment",
            ),
        ),
    ]
