# Generated by Django 3.1.1 on 2020-12-25 10:49

import django.db.models.deletion
from django.db import migrations, models

import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("payment", "0019_auto_20201225_0631"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directmerchantpayment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="payment",
        ),
        migrations.AddField(
            model_name="directmerchantpayment",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_merchant_payments",
                to="payment.transaction",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="charge_status",
            field=db.models.fields.enum.ChoiceEnumField(default=0),
        ),
        migrations.AddField(
            model_name="refund",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="payment.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="directmerchantpayment",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_merchant_payments",
                to="payment.payment",
            ),
        ),
        migrations.AlterField(
            model_name="directmerchantpayment",
            name="payment_qrcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_merchant_payments",
                to="payment.paymentqrcode",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="order.order",
            ),
        ),
    ]
