# Generated by Django 3.1.1 on 2020-12-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20201225_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='payment.transaction'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='payment.payment'),
        ),
    ]
