# Generated by Django 3.1.1 on 2020-12-25 11:04

import db.models.fields.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20201225_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_ip_address',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_process',
            field=db.models.fields.enum.ChoiceEnumField(default=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='charge_status',
            field=db.models.fields.enum.ChoiceEnumField(),
        ),
    ]
