# Generated by Django 3.1.1 on 2020-12-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0023_auto_20201225_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="individual_ach_id",
            field=models.CharField(
                blank=True, default=None, max_length=32, null=True, unique=True
            ),
        ),
    ]
