# Generated by Django 3.1.1 on 2020-12-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0025_transaction_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_request",
                to="payment.transaction",
            ),
        ),
    ]
