# Generated by Django 3.1.1 on 2020-12-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0026_auto_20201225_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund",
                to="payment.transaction",
            ),
        ),
    ]
