# Generated by Django 3.1.1 on 2020-12-28 11:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import db.models.fields.choice
import db.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0027_auto_20201225_1747"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="tracking_number",
            new_name="transaction_tracking_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_tracking_id",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_disputed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DisputeTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "dispute_tracking_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("status", db.models.fields.enum.ChoiceEnumField()),
                (
                    "type",
                    db.models.fields.choice.ChoiceCharEnumField(max_length=32),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputetransaction_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputetransaction_deleted_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute",
                        to="payment.transaction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputetransaction_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispute_transaction",
            },
        ),
    ]
