# Generated by Django 3.1.1 on 2020-12-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0025_auto_20201228_1105"),
        ("payment", "0028_auto_20201228_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmerchantpayment",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_merchant_payments",
                to="merchant.accountmember",
            ),
        ),
    ]
