# Generated by Django 3.1.1 on 2020-12-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0032_refund_refund_tracking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputetransaction",
            name="reason",
            field=models.TextField(default=""),
        ),
    ]
