# Generated by Django 3.1.1 on 2020-12-30 18:06

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0033_disputetransaction_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disputetransaction",
            old_name="reason",
            new_name="reason_message",
        ),
        migrations.AddField(
            model_name="disputetransaction",
            name="reason_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="other", max_length=32
            ),
        ),
    ]
