# Generated by Django 3.1.5 on 2021-01-18 16:29

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0036_payment_total_tip_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ach_return_code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="failure_reason_message",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="transaction",
            name="failure_reason_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="na", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_sender_failure",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="min_access_balance_required",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_balance_at_checkout",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
    ]
