# Generated by Django 3.1.5 on 2021-01-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210114_0554'),
        ('banking', '0007_auto_20210115_1208'),
        ('payment', '0037_auto_20210118_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ach_return_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_return_transactions', to='account.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ach_return_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_return_transactions', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ach_return_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ach_return_explaination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_bearer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_for_transactions', to='account.account'),
        ),
    ]
