# Generated by Django 3.1.5 on 2021-01-20 11:14

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0038_auto_20210119_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receiver_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                max_length=128, default="not_started"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                max_length=128, default="not_started"
            ),
        ),
    ]
