# Generated by Django 3.1.5 on 2021-01-20 13:02

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0039_auto_20210120_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="failure_reason_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="na", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receiver_status",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=128),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_status",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=128),
        ),
    ]
