# Generated by Django 3.1.5 on 2021-01-27 06:53

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0042_auto_20210127_0627"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionevent",
            name="event_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactionevent",
            name="event_type",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=128),
        ),
    ]
