# Generated by Django 3.1.5 on 2021-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0043_auto_20210127_0653"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_receiver_tranfer_complete",
            field=models.BooleanField(default=False),
        ),
    ]
