# Generated by Django 3.1.5 on 2021-02-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0045_auto_20210206_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputetransaction",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disputetransaction",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="disputetransaction",
            name="resolution",
            field=models.TextField(default=""),
        ),
    ]
