# Generated by Django 3.1.5 on 2021-02-07 07:47

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0046_auto_20210207_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disputetransaction",
            name="status",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=64),
        ),
    ]
