# Generated by Django 3.1.5 on 2021-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0047_auto_20210207_0747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sender_balance_at_checkout",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
    ]
