# Generated by Django 3.1.5 on 2021-03-10 07:47

from django.db import migrations


def migrate_data(apps, schema_editor):
    MerchantAccount = apps.get_model("account", "MerchantAccount")
    MerchantReceiveLimit = apps.get_model("payment", "MerchantReceiveLimit")
    for merchant in MerchantAccount.objects.all():
        receive_limit = MerchantReceiveLimit.objects.filter(
            merchant_id=merchant.id
        )
        if not receive_limit.exists():
            MerchantReceiveLimit.objects.create(
                merchant_id=merchant.id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0048_merchantreceivelimit"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
