# Generated by Django 3.1.5 on 2021-03-12 07:35

import django.db.models.deletion
from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0013_auto_20210308_1135"),
        ("banking", "0019_auto_20210212_1535"),
        ("payment", "0052_auto_20210312_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="direct_merchant_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="payment.directmerchantpayment",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="payment.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient_source_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                blank=True, default="bank_account", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="payment.refund",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reward_usage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="reward.rewardusage",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_source_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                blank=True, default="bank_account", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_payment_request",
                to="payment.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="recipient_bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="recipient_transactions",
                to="banking.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sender_transactions",
                to="banking.bankaccount",
            ),
        ),
    ]
