# Generated by Django 3.1.5 on 2021-03-12 12:58

import db.models.fields.enum
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0054_auto_20210312_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmerchantpayment',
            name='status',
            field=db.models.fields.enum.ChoiceEnumField(),
        ),
    ]
