# Generated by Django 3.1.5 on 2021-03-13 09:26

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0055_auto_20210312_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="refund_note",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="refund",
            name="refund_reason",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="returns", max_length=256
            ),
        ),
    ]
