# Generated by Django 3.1.5 on 2021-03-14 16:01

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0057_auto_20210314_1601"),
    ]

    operations = []
