# Generated by Django 3.1.5 on 2021-03-15 14:27

import django.db.models.deletion
from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0054_featureaccessrole_merchant_settings"),
        ("payment", "0058_auto_20210315_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_requuests",
                to="merchant.accountmember",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refund_reason",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=256),
        ),
    ]
