# Generated by Django 3.1.5 on 2021-03-19 14:29

from django.db import migrations

import db.models.fields.choice


def migrate_data(apps, schema_editor):
    Transaction = apps.get_model("payment", "Transaction")
    for transaction in Transaction.objects.all():
        try:
            direct_merchant_payment = transaction.direct_merchant_payments
            transaction.direct_merchant_payment = direct_merchant_payment
        except Exception:
            pass

        try:
            payment_request = transaction.related_payment_request
            transaction.payment_request = payment_request
        except Exception:
            pass

        try:
            refund_payment = transaction.refund
            transaction.refund_payment = refund_payment
        except Exception:
            pass
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0059_auto_20210315_1427"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
