# Generated by Django 3.1.5 on 2021-03-19 14:49

from decimal import Decimal

from django.db import migrations

import db.models.fields.choice


def migrate_data(apps, schema_editor):
    Refund = apps.get_model("payment", "Refund")
    for refund in Refund.objects.all():
        try:
            if refund.requested_items_value == Decimal(0):
                refund.requested_items_value = refund.amount
                refund.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0060_auto_20210319_1429"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
