# Generated by Django 3.1.5 on 2021-03-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0055_auto_20210318_1111"),
        ("payment", "0061_auto_20210319_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="merchant.accountmember",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_requests",
                to="merchant.accountmember",
            ),
        ),
    ]
