# Generated by Django 3.1.5 on 2021-04-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0062_auto_20210319_0653"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentqrcode",
            name="register_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
