# Generated by Django 3.1.5 on 2021-04-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0063_paymentqrcode_register_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payment.paymentqrcode",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_requests",
                to="payment.paymentqrcode",
            ),
        ),
    ]
