# Generated by Django 3.1.5 on 2021-05-03 04:49

from django.db import migrations


def migrate_data(apps, schema_editor):
    PaymentQrCode = apps.get_model("payment", "PaymentQrCode")
    MerchantAccount = apps.get_model("account", "MerchantAccount")
    for merchant in MerchantAccount.objects.all():
        for index, qrcode in enumerate(
            PaymentQrCode.objects.filter(merchant_id=merchant.id)
        ):
            qrcode.register_name = f"Register {index+1}"
            qrcode.save()


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0064_auto_20210427_0443"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
