# Generated by Django 3.1.1 on 2020-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_number_suffix",
            field=models.CharField(default="1234", max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="bank_logo_base64",
            field=models.TextField(
                default="wdedesfr3245r47f4gfc7v65t47643t764t43675gdnfg74g67fg"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(default="Bank", max_length=64),
            preserve_default=False,
        ),
    ]
