# Generated by Django 3.1.5 on 2021-01-20 14:53

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0008_auto_20210120_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="dwolla_funding_source_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                max_length=32, default="na"
            ),
        ),
    ]
