# Generated by Django 3.1.5 on 2021-01-21 12:20

import db.models.fields.choice
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_bankaccount_dwolla_funding_source_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='dwolla_funding_source_status',
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=32, default="na"),
        ),
    ]
