# Generated by Django 3.1.5 on 2021-01-22 16:25

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0010_auto_20210121_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="dwolla_funding_source_status",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=32),
        ),
    ]
