# Generated by Django 3.1.5 on 2021-01-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_bankaccount_is_reverification_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_reverification_needed',
        ),
    ]
