# Generated by Django 3.1.5 on 2021-02-11 09:33

import db.models.fields.choice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_remove_bankaccount_is_reverification_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='verification_provider',
            field=db.models.fields.choice.ChoiceCharEnumField(default='plaid', max_length=32),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='plaid_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='plaid_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
