# Generated by Django 3.1.5 on 2021-02-11 11:21

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0015_auto_20210211_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_account_type",
            field=models.CharField(default="checking", max_length=32),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number_suffix",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_logo_base64",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="plaid_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="pending", max_length=32
            ),
        ),
    ]
