# Generated by Django 3.1.5 on 2021-02-12 12:39

from django.db import migrations, models

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0016_auto_20210211_1121"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="max_attempts_exceeded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="micro_deposit_status",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="na", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="verification_type",
            field=db.models.fields.choice.ChoiceCharEnumField(
                default="instant", max_length=32
            ),
        ),
    ]
