# Generated by Django 3.1.5 on 2021-02-12 12:41

from django.db import migrations

import db.models.fields.choice


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0017_auto_20210212_1239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="micro_deposit_status",
            field=db.models.fields.choice.ChoiceCharEnumField(max_length=32),
        ),
    ]
