# Generated by Django 3.1.5 on 2021-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0018_auto_20210212_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
